# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'MUCLight' do

  pod "XMPPFramework", :path => "../../../"
  pod 'KissXML/SwiftNSXML', '~> 5.1.2'
  pod 'MBProgressHUD', '~> 0.9.2'

end